# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
  - name: ado_service_connection_aml_ws
    value: GSC-NONP-->GSC-NALCOWATER-001-D-SC
  - name: resource_group
    value: GSC-NALCOWATER-001-D
  - name: aml_workspace
    value: azgscamlws01
  - name: location
    value: useast2

trigger:
- none


stages:
- stage: CreateFeatureData 
  displayName: Create Feature Data
  jobs:      
    - job: DataProcessing
      steps:
      - task: Bash@3
        displayName: Install AZ CLI
        inputs:
          targetType: 'inline'
          script: |
            set -e # fail on error
            sudo apt install -y python3-pip
            sudo apt install curl -y
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            sudo apt-get update
            sudo apt-get install azure-cli
      - task: AzureCLI@2
        displayName: Install AML CLI
        inputs:
          azureSubscription: $(ado_service_connection_aml_ws)
          scriptType: bash
          scriptLocation: inlineScript
          workingDirectory: code/
          inlineScript: |
            set -e # fail on error
            az version
            az extension add -n ml -y
            az configure --defaults group=$(resource_group) workspace=$(aml_workspace) location=$(location)
      - task: AzureCLI@2
        displayName: Submit pipeline
        inputs:
          azureSubscription: $(ado_service_connection_aml_ws)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az ml workspace update --name $(aml_workspace) --resource-group $(resource_group) --image-build-compute gscamlcluster01
            az ml environment create --file EcoLabOptimization/ECL_EDSP_ScheduleOptimization/mlops/endpoint/environment.yml
            az ml online-endpoint create -f EcoLabOptimization/ECL_EDSP_ScheduleOptimization/mlops/endpoint/model-endpoint.yml
            az ml online-deployment create -f EcoLabOptimization/ECL_EDSP_ScheduleOptimization/mlops/endpoint/model-deployment.yml --all-traffic || {
              az ml online-deployment update -f EcoLabOptimization/ECL_EDSP_ScheduleOptimization/mlops/endpoint/model-deployment.yml;
            }

