$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: clearing-production-schedule-deployment
endpoint_name: clearing-production-schedule
code_configuration:
  code: src
  scoring_script: run_simulation.py
environment:
  build:
    path: ..
    dockerfile_path: envs/Dockerfile
instance_type: Standard_DS3_v2
instance_count: 1