$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: clearing-production-schedule
endpoint_name: production-schedule-endpoint
code_configuration:
  code: src
  scoring_script: run_simulation.py
environment:
  build:
    path: envs
instance_type: Standard_DS3_v2
instance_count: 1