$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: production-schedule-deployment
endpoint_name: clearing-production-schedule
code_configuration:
  code: src
  scoring_script: run_simulation.py
environment: azureml:production-schedule-env@latest
instance_type: Standard_DS3_v2
instance_count: 1